name: CI

on:
  push:
    branches:
      - main

  pull_request:

env:
  NODE_VERSION: 24
  API_DIR: api

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.API_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ env.API_DIR }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.API_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ env.API_DIR }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
